#!/bin/bash

echo --------------------
echo $1 >> zoomlinkcatcher.out
echo $2 >> zoomlinkcatcher.out
echo $3 >> zoomlinkcatcher.out
echo $4 >> zoomlinkcatcher.out
echo $5 >> zoomlinkcatcher.out
echo --------------------
